version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/application
    ports:
      - "3000:3000"
    environment:
      
    depends_on:
      - db

      

version: '3'
volumes:
  postgres_data: {}
services:
  app:
    build:
      context: ".."
      dockerfile: dockerfiles/Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
    environment:
      - DB_HOST:db
      - DB_USER:postgres
      - DB_PASSWORD:supporterhub_password
    volumes:
      - .:/app
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:supporterhub_password

